### ISSUE TITLE
CI test fails - Test::When is not installed

### ISSUE THREAD

**Issue by melezhik** [vrurg/Perl6-AttrX-Mooish#2]
Hi!

Here is the log - http://sparrowhub.io:2222/report/143

I guess Test::When needs to be added to a `META.json` file

HTH

Aleksei

**Comment by vrurg** [comment]
It is in `test-depends` key already.

**Comment by melezhik** [comment]
I see, for some reasons it’s not triggered though …

**Comment by melezhik** [comment]
@ugexe  @atroxaper I wonder if “zef install . —depsonly && racoco -l --html 2>&1“ should  trigger test-depends dependencies installation ?

**Comment by vrurg** [comment]
I can tell you. No, it shouldn't. You also need `--test-depends`.

**Comment by ugexe** [comment]
`zef install . --deps-only` will certainly install test dependencies, so I'm not sure if your example command is correct for reproducing your issue. I also can't tell what any of the commands are so I can only take a guess (which @vrurg already suggests): If you use `--/test` then it implies `--/test-depends`, so if you don't want that then be explicit `--/test --test-depends`.

**Comment by melezhik** [comment]
The actual command is - https://github.com/melezhik/sparkyci/blob/main/sparky/raku/sparrowfile#L94 , so thanks Nick , I need to add —test—depends as well

**Comment by melezhik** [comment]
looks good now - http://sparrowhub.io:2222/report/225
